# Generated by Django 2.0.7 on 2018-07-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='aprovado',
            field=models.NullBooleanField(default=None),
        ),
    ]
