# Generated by Django 2.0.7 on 2018-07-10 19:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180710_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
