# Generated by Django 2.0.7 on 2018-07-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180710_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
